### ISSUE TITLE
Edge detection

### ISSUE THREAD

**Issue by swaggalolz** [ArtemKravchenko94/PassportScanner#13]
Realize edge detection. Kenny method or something else.
https://en.wikipedia.org/wiki/Edge_detection
https://habrahabr.ru/post/114452/
http://ict.edu.ru/ft/002397/num4confld.pdf

**Comment by ArtemKravchenko94** [comment]
WIP

**Comment by ArtemKravchenko94** [comment]
Dev Done, Canny detection was implemented.
